name: Set up Node
description: Set up Node

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install root project node packages
      uses: nick-fields/retry@3f757583fb1b1f940bc8ef4bf4734c8dc02a5847
      with:
        timeout_minutes: 30
        max_attempts: 3
        command: npm ci