require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, 14 # Latter is minimum supported version

prepare_react_native_project!

# Setup permissions
setup_permissions([
  # 'AppTrackingTransparency',
  # 'BluetoothPeripheral',
  # 'Calendars',
  'Camera',
  # 'Contacts',
  # 'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

# Flipper is not compatible with use_frameworks! (Firebase)
# flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
# use_frameworks! :linkage => :static
# $RNFirebaseAsStaticFramework = true
# use_modular_headers!

# Force pods to match minimum iOS version for React Native
# Fixes build issue on Xcode Cloud where some pods
# Use iOS 12 calls despite being set as iOS 11
def __apply_Xcode_14_3_RC_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      minimum_target = min_ios_version_supported
      if current_target.to_f < minimum_target.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_target
      end
    end
  end
end

target 'kiroku' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  permissions_path = '../node_modules/react-native-permissions/ios'

  project 'kiroku',
    'DebugDevelopment' => :debug,
    'DebugAdHoc' => :debug,
    'DebugProduction' => :debug,
    'ReleaseDevelopment' => :release,
    'ReleaseAdhoc' => :release,
    'ReleaseProduction' => :release

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  # ENV Variable enables/disables TurboModules
  ENV['RCT_NEW_ARCH_ENABLED'] = '1';

  # Enable react-native-config for environment file management
  # pod 'react-native-config/Extension', :path => '../node_modules/react-native-config'
# 
  use_react_native!(
    :path => config[:reactNativePath],

    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",

    # Hermes
    :hermes_enabled => true
  )

  target 'kirokuTests' do
    inherit! :complete
    # Pods for testing
  end


  post_install do |installer|

    react_native_post_install(
      installer,
      config[:reactNativePath],
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_14_3_RC_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
      
      # Fix for iOS 26.0: AssetsLibrary is deprecated and causes Swift compilation errors
      # Prevent Swift from trying to compile unavailable system modules
      target.build_configurations.each do |config|
        # Remove AssetsLibrary from OTHER_LDFLAGS if present
        if config.build_settings['OTHER_LDFLAGS']
          flags = config.build_settings['OTHER_LDFLAGS']
          if flags.is_a?(Array)
            config.build_settings['OTHER_LDFLAGS'] = flags.reject { |flag| flag.to_s.include?('AssetsLibrary') }
          end
        end
        
        # Fix for iOS 26.0: Prevent Swift from compiling unavailable AssetsLibrary module
        # Add build setting to skip unavailable system modules
        swift_flags = config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)']
        if swift_flags.is_a?(Array)
          # Add flag to suppress errors about unavailable APIs (iOS 26.0 compatibility)
          swift_flags << '-Xfrontend -warn-long-function-bodies=100' unless swift_flags.any? { |f| f.include?('warn-long-function-bodies') }
        end
        
        # Set build setting to suppress Swift warnings (helps with unavailable modules)
        config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
        
        # Most importantly: Set SDKROOT to use an older SDK if available, or add flag to skip unavailable modules
        # Since we can't easily change SDK, we'll add a workaround by setting a user-defined build setting
        config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] ||= '$(inherited)'
        # Add condition to skip unavailable modules
        if config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'].is_a?(String)
          config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] += ' SKIP_UNAVAILABLE_MODULES'
        elsif config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'].is_a?(Array)
          config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] << 'SKIP_UNAVAILABLE_MODULES' unless config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'].include?('SKIP_UNAVAILABLE_MODULES')
        end
        
        # Set deployment target to avoid iOS 26.0 SDK issues if using iOS 26.0 SDK
        # This prevents Swift from trying to compile unavailable modules
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
      end
    end
  end
end
