name: 'Announce Failed Workflow in Discord'
description: 'Post failed workflow in Discord #announce channel'

inputs:
  DISCORD_WEBHOOK_URL:
    description: 'URL of the Discord webhook'
    required: true

runs:
  using: composite
  steps:
    - name: Send Discord Notification
      shell: bash
      run: |
        curl -s -X POST "$DISCORD_WEBHOOK" \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"💥 **${{ github.repository }}** failed on [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) workflow 💥\"}"
      env:
        DISCORD_WEBHOOK: ${{ inputs.DISCORD_WEBHOOK_URL }}
