name: Set up Bun
description: Set up Bun

outputs:
  cache-hit:
    description: Was there a cache hit on the main node_modules?
    value: ${{ steps.cache-node-modules.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        cache: bun
        cache-dependency-path: |
          package-lock.json

    - id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json', 'patches/**') }}

    - name: Install root project node packages
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: nick-fields/retry@3f757583fb1b1f940bc8ef4bf4734c8dc02a5847
      with:
        timeout_minutes: 30
        max_attempts: 3
        command: bun install
