name: Create New Version

on:
  pull_request:
    branches:
        - None
    types: [closed]

jobs:
  generate-new-version:
    runs-on: macos-latest
    # Run only if the PR is merged
    if: github.event.pull_request.merged == true
    outputs:
      NEW_VERSION: ${{ steps.bump-version.outputs.NEW_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Determine Input Based on PR labels
        id: pr-label-analysis
        uses: actions/github-script@v3
        with:
          script: |
              const pr = context.payload.pull_request;
              const labelMap = {
                  'v-build': 'BUILD',
                  'v-patch': 'PATCH',
                  'v-minor': 'MINOR',
                  'v-major': 'MAJOR'
              };
              // Find the first label that matches the keys in labelMap
              const matchedLabel = pr.labels.find(label => labelMap[label.name]);
              const inputValue = matchedLabel ? labelMap[matchedLabel.name] : 'BUILD';
              return inputValue;

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        id: bump-version
        if: steps.pr-label-analysis.outputs.result != ''
        env:
          SEMVER_LEVEL: ${{ steps.pr-label-analysis.outputs.result }}
        run: node .github/actions/javascript/bumpVersion/bumpVersion.js

      - name: Commit new version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Version-O-Bot"
          git add \
            ./package.json \
            ./package-lock.json \
            ./android/app/build.gradle \
            ./ios/kiroku/Info.plist \
            ./ios/kirokuTests/Info.plist
          git commit -m "Update version to ${{ steps.bump-version.outputs.NEW_VERSION }}"

      - name: Update the branch
        run: git push origin workflow-tests-2