name: Bump Version

on:
  workflow_dispatch:
    inputs:
      SEMVER_LEVEL:
        description: One of {BUILD, PATCH, MINOR, MAJOR}
        required: true
        default: BUILD
        type: string

  workflow_call:
    inputs:
      SEMVER_LEVEL:
        description: One of {BUILD, PATCH, MINOR, MAJOR}
        required: false
        default: BUILD
        type: string

jobs:
  create-new-version:
    runs-on: macos-latest

    outputs:
      NEW_VERSION: ${{ steps.bump-version.outputs.NEW_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        id: bump-version
        run: |
          SEMVER_LEVEL=${{ inputs.SEMVER_LEVEL }} node .github/actions/javascript/bumpVersion/bumpVersion.js

      - name: Commit new version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Version-O-Bot"
          git add \
            ./package.json \
            ./package-lock.json \
            ./android/app/build.gradle \
            ./ios/kiroku/Info.plist \
            ./ios/kirokuTests/Info.plist
          git commit -m "Update version to ${{ steps.bump-version.outputs.NEW_VERSION }}"

      - name: Update the branch
        run: git push origin workflow-tests