name: Build and deploy apps for testing

on:
  workflow_dispatch:
    inputs:
      PULL_REQUEST_NUMBER:
        description: Pull Request number for correct placement of apps
        required: true
  pull_request:
    types: [opened, synchronize, labeled]
    branches: ['dev']

jobs:
  getBranchRef:
    runs-on: ubuntu-latest
    outputs:
      REF: ${{steps.getHeadRef.outputs.REF}}
    steps:
      - name: Checkout
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - name: Check if pull request number is correct
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: getHeadRef
        run: |
          set -e
          gh pr checkout ${{ github.event.inputs.PULL_REQUEST_NUMBER }}
          echo "REF=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  android:
    name: Build and deploy Android for testing
    runs-on: ubuntu-latest
    needs: [getBranchRef]
    env:
      PULL_REQUEST_NUMBER: ${{ github.event.number || github.event.inputs.PULL_REQUEST_NUMBER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || needs.getBranchRef.outputs.REF }}

      - name: Create .env.development file based on staging and add PULL_REQUEST_NUMBER env to it
        run: |
          echo "${{ secrets.DEV_ENV_FILE }}" > .env.development
          echo "PULL_REQUEST_NUMBER=$PULL_REQUEST_NUMBER" >> .env.development

      - name: Setup Bun
        uses: ./.github/actions/composite/setupBun

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Setup Ruby
        uses: ruby/setup-ruby@a05e47355e80e57b9a67566a813648fa67d92011
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Decrypt keystore
        run: cd android/app && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output kiroku-play-key.keystore kiroku-play-key.keystore.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Decrypt json key
        run: cd android/app && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output android-fastlane-json-key.json android-fastlane-json-key.json.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Run Fastlane beta test
        id: runFastlaneBetaTest
        run: bundle exec fastlane android build_internal
        env:
          MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: ./android_paths.json

  iOS:
    name: Build and deploy iOS for testing
    needs: [getBranchRef]
    env:
      PULL_REQUEST_NUMBER: ${{ github.event.number || github.event.inputs.PULL_REQUEST_NUMBER }}
      DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || needs.getBranchRef.outputs.REF }}

      - name: Create .env.development file based on staging and add PULL_REQUEST_NUMBER env to it
        run: |
          echo "${{ secrets.DEV_ENV_FILE }}" > .env.development
          echo "PULL_REQUEST_NUMBER=$PULL_REQUEST_NUMBER" >> .env.development

      - name: Setup Bun
        uses: ./.github/actions/composite/setupBun

      - name: Setup XCode
        run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app

      - name: Setup Ruby
        uses: ruby/setup-ruby@a05e47355e80e57b9a67566a813648fa67d92011
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Cache Pod dependencies
        uses: actions/cache@v4
        id: pods-cache
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-cache-${{ hashFiles('ios/Podfile.lock', 'firebase.json') }}
          restore-keys: ${{ runner.os }}-pods-cache-

      - name: Compare Podfile.lock and Manifest.lock
        id: compare-podfile-and-manifest
        run: echo "IS_PODFILE_SAME_AS_MANIFEST=${{ hashFiles('ios/Podfile.lock') == hashFiles('ios/Pods/Manifest.lock') }}" >> "$GITHUB_OUTPUT"

      - name: Install cocoapods
        uses: nick-invision/retry@0711ba3d7808574133d713a0d92d2941be03a350
        if: steps.pods-cache.outputs.cache-hit != 'true' || steps.compare-podfile-and-manifest.outputs.IS_PODFILE_SAME_AS_MANIFEST != 'true'
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: cd ios && bundle exec pod install

      - name: Decrypt Development profile
        run: cd ios && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output Kiroku_Development.mobileprovision Kiroku_Development.mobileprovision.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Decrypt certificate
        run: cd ios && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output devCertificates.p12 devCertificates.p12.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Run Fastlane
        run: bundle exec fastlane ios build_internal
        env:
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios
          path: ./ios_paths.json
