name: Call Workflow

on:
  push:
    branches:
      - no-branch

jobs:
  call-create-new-version-workflow:
    uses: PetrCala/Kiroku/.github/workflows/createNewVersion.yml@workflow-tests
    with:
      SEMVER_LEVEL: BUILD