name: Call Workflow

on:
  push:
    branches:
      - workflow-tests

jobs:
  call-create-new-version-workflow:
    uses: PetrCala/Kiroku/.github/workflows/createNewVersion.yml@workflow-tests
    with:
      SEMVER_LEVEL: BUILD
    # secrets:
    #   GH_TOKEN: ${{ secrets.GH_TOKEN }}